name: clipseq
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'bioconda'
- !!python/unicode
  'r'
- !!python/unicode
  'defaults'
dependencies:
- bioconda::bamtools=2.4.0=3
- bioconda::bcftools=1.3.1=1
- bioconda::bedops=2.4.20=0
- bioconda::bedtools=2.26.0=0
- bioconda::bioconductor-annotate=1.50.0=r3.3.1_1
- bioconda::bioconductor-annotationdbi=1.36.0=r3.3.1_1
- bioconda::bioconductor-biobase=2.32.0=0
- bioconda::bioconductor-biocgenerics=0.20.0=r3.3.1_0
- bioconda::bioconductor-biocparallel=1.6.6=r3.3.1_0
- bioconda::bioconductor-biomart=2.28.0=r3.3.1_0
- bioconda::bioconductor-biostrings=2.40.0=r3.3.1_0
- bioconda::bioconductor-deseq2=1.12.4=r3.3.1_3
- bioconda::bioconductor-edger=3.14.0=r3.3.1_1
- bioconda::bioconductor-genefilter=1.54.2=r3.3.1_0
- bioconda::bioconductor-geneplotter=1.50.0=r3.3.1_0
- bioconda::bioconductor-genomeinfodb=1.8.7=r3.3.1_0
- bioconda::bioconductor-genomicalignments=1.10.0=r3.3.1_0
- bioconda::bioconductor-genomicfeatures=1.26.0=r3.3.1_2
- bioconda::bioconductor-genomicranges=1.26.1=r3.3.1_1
- bioconda::bioconductor-iranges=2.8.0=r3.3.1_0
- bioconda::bioconductor-limma=3.29.0=r3.3.1_0
- bioconda::bioconductor-rsamtools=1.26.1=r3.3.1_0
- bioconda::bioconductor-rtracklayer=1.34.1=r3.3.1_0
- bioconda::bioconductor-s4vectors=0.12.0=r3.3.1_0
- bioconda::bioconductor-summarizedexperiment=1.4.0=r3.3.1_0
- bioconda::bioconductor-tximport=1.0.3=r3.3.1_0
- bioconda::bioconductor-xvector=0.12.1=r3.3.1_0
- bioconda::bioconductor-zlibbioc=1.18.0=r3.3.1_0
- bioconda::biopython=1.68=py35_0
- bioconda::bowtie=1.1.2=py35_2
- bioconda::bowtie2=2.2.8=py35_2
- bioconda::cutadapt=1.12=py35_0
- bioconda::dropbox=5.2.1=py35_0
- bioconda::fastqc=0.11.5=1
- bioconda::fastx_toolkit=0.0.14=2
- bioconda::gnuplot=5.0.4=ncurses5.9_0
- bioconda::htslib=1.3.2=0
- bioconda::intervaltree=2.1.0=py35_0
- bioconda::java-jdk=8.0.92=1
- bioconda::kallisto=0.43.0=1
- bioconda::libgd=2.2.3=1
- bioconda::libgtextutils=0.7=2
- bioconda::libxml2=2.9.3=0
- bioconda::multiqc=0.8=py35_0
- bioconda::novoalign=3.04.04=3
- bioconda::perl-gd=2.56=4
- bioconda::perl-gdgraph=1.49=2
- bioconda::perl-gdgraph-histogram=1.1=0
- bioconda::perl-gdtextutil=0.86=2
- bioconda::perl-perlio-gzip=0.19=0
- bioconda::perl-threaded=5.22.0=10
- bioconda::picard=2.7.1=py35_0
- bioconda::piranha=1.2.1=gsl1.16_2
- bioconda::pybedtools=0.7.8=py35_1
- bioconda::pysam=0.9.0=py35_1
- bioconda::pysftp=0.2.8=py35_0
- bioconda::qualimap=2.2=0
- bioconda::r-bh=1.60.0_2=r3.3.1_0
- bioconda::r-catools=1.17.1=r3.3.1_0
- bioconda::r-digest=0.6.9=r3.3.1_0
- bioconda::r-docopt=0.4.3.3=r3.3.1_0
- bioconda::r-futile.logger=1.4.1=r3.3.1_0
- bioconda::r-futile.options=1.0.0=r3.3.1_0
- bioconda::r-getopt=1.20.0=r3.3.1_0
- bioconda::r-ggplot2=2.1.0=r3.3.1_0
- bioconda::r-gplots=2.17.0=r3.3.1_0
- bioconda::r-lambda.r=1.1.7=r3.3.1_0
- bioconda::r-locfit=1.5_9.1=r3.3.1_0
- bioconda::r-magrittr=1.5=r3.3.1_0
- bioconda::r-pheatmap=1.0.8=r3.3.1_0
- bioconda::r-readr=0.2.2=r3.3.1_0
- bioconda::r-rjson=0.2.15=r3.3.1_0
- bioconda::r-snow=0.4_1=r3.3.1_0
- bioconda::r-statmod=1.4.22=r3.3.1_0
- bioconda::rmap=2.1=0
- bioconda::samtools=1.3.1=5
- bioconda::simplejson=3.8.1=py35_0
- bioconda::snakemake=3.9.0=py35_0
- bioconda::sra-tools=2.7.0=0
- bioconda::star=2.5.2b=0
- bioconda::trim-galore=0.4.1=0
- bioconda::ucsc-bedgraphtobigwig=332=0
- bioconda::ucsc-bedsort=332=0
- bioconda::ucsc-bedtobigbed=332=0
- bioconda::ucsc-liftover=324=0
- bioconda::ucsc-wigtobigwig=332=0
- bioconda::viennarna=2.3.1=1
- bioconda::xopen=0.1.0=py35_0
- bioconda::zagros=1.0.0=gsl1.16_0
- bzip2=1.0.6=3
- cairo=1.12.18=6
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py35_0
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2016.9.26=0
- conda-forge::certifi=2016.9.26=py35_0
- conda-forge::click=6.6=py35_0
- conda-forge::curl=7.49.1=1
- conda-forge::cycler=0.10.0=py35_0
- conda-forge::cython=0.25.1=py35_0
- conda-forge::dbus=1.10.10=0
- conda-forge::decorator=4.0.10=py35_0
- conda-forge::docutils=0.12=py35_0
- conda-forge::expat=2.1.0=2
- conda-forge::filechunkio=1.8=py35_0
- conda-forge::ftputil=3.3.1=py35_0
- conda-forge::gettext=0.19.7=1
- conda-forge::glib=2.48.0=4
- conda-forge::gmp=6.1.1=1
- conda-forge::gsl=1.16=0
- conda-forge::gst-plugins-base=1.8.0=0
- conda-forge::gstreamer=1.8.0=1
- conda-forge::hdf5=1.8.17=7
- conda-forge::ipython_genutils=0.1.0=py35_0
- conda-forge::jinja2=2.8=py35_1
- conda-forge::libffi=3.2.1=2
- conda-forge::libiconv=1.14=3
- conda-forge::libpng=1.6.26=0
- conda-forge::libuuid=1.0.3=1
- conda-forge::libxcb=1.12=0
- conda-forge::markupsafe=0.23=py35_0
- conda-forge::mmtf-python=1.0.4=py35_0
- conda-forge::mpc=1.0.3=2
- conda-forge::mpfr=3.1.4=2
- conda-forge::msgpack-python=0.4.8=py35_0
- conda-forge::ncurses=5.9=10
- conda-forge::nose=1.3.7=py35_2
- conda-forge::numexpr=2.6.1=np111py35_0
- conda-forge::numpy=1.11.2=py35_blas_openblas_201
- conda-forge::openblas=0.2.18=6
- conda-forge::openssl=1.0.2h=3
- conda-forge::pandas=0.19.1=np111py35_0
- conda-forge::paramiko=1.17.2=py35_0
- conda-forge::patsy=0.4.1=py35_0
- conda-forge::pcre=8.38=1
- conda-forge::pexpect=4.2.1=py35_0
- conda-forge::pickleshare=0.7.3=py35_0
- conda-forge::pillow=3.2.0=py35_0
- conda-forge::pip=9.0.1=py35_0
- conda-forge::pixman=0.32.6=0
- conda-forge::ptyprocess=0.5.1=py35_0
- conda-forge::pycrypto=2.6.1=py35_0
- conda-forge::pygments=2.1.3=py35_1
- conda-forge::pyparsing=2.1.10=py35_0
- conda-forge::pytables=3.3.0=np111py35_0
- conda-forge::python=3.5.2=2
- conda-forge::python-dateutil=2.6.0=py35_0
- conda-forge::pytz=2016.7=py35_0
- conda-forge::pyyaml=3.11=py35_0
- conda-forge::readline=6.2=0
- conda-forge::requests=2.12.1=py35_0
- conda-forge::scipy=0.18.1=np111py35_blas_openblas_200
- conda-forge::seaborn=0.7.1=py35_0
- conda-forge::setuptools=29.0.1=py35_1
- conda-forge::simplegeneric=0.8.1=py35_0
- conda-forge::sip=4.18=py35_0
- conda-forge::six=1.10.0=py35_1
- conda-forge::sortedcontainers=1.5.3=py35_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::statsmodels=0.6.1=np111py35_0
- conda-forge::tk=8.5.19=0
- conda-forge::traitlets=4.3.0=py35_0
- conda-forge::urllib3=1.18.1=py35_0
- conda-forge::wcwidth=0.1.7=py35_0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::wrapt=1.10.8=py35_0
- conda-forge::xz=5.2.2=0
- conda-forge::yaml=0.1.6=0
- conda-forge::zlib=1.2.8=3
- ecdsa=0.13=py35_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- gcc=4.8.5=7
- icu=54.1=0
- jbig=2.1=0
- jpeg=8d=2
- libgfortran=3.0.0=1
- libtiff=4.0.6=2
- lzo=2.06=0
- matplotlib=1.5.3=np111py35_1
- mkl=11.3.3=0
- mysql=5.5.24=0
- pyqt=5.6.0=py35_0
- qt=5.6.0=1
- r::cloog=0.18.0=0
- r::harfbuzz=0.9.35=6
- r::isl=0.12.2=0
- r::libgcc=4.8.5=1
- r::pango=1.36.8=3
- r::r=3.3.1=r3.3.1_0
- r::r-acepack=1.3_3.3=r3.3.1_2
- r::r-assertthat=0.1=r3.3.1_4
- r::r-base=3.3.1=3
- r::r-bitops=1.0_6=r3.3.1_2
- r::r-boot=1.3_18=r3.3.1_0
- r::r-chron=2.3_47=r3.3.1_0
- r::r-class=7.3_14=r3.3.1_0
- r::r-cluster=2.0.4=r3.3.1_0
- r::r-codetools=0.2_14=r3.3.1_0
- r::r-colorspace=1.2_6=r3.3.1_0
- r::r-curl=0.9.7=r3.3.1_0
- r::r-data.table=1.9.6=r3.3.1_0
- r::r-dbi=0.4_1=r3.3.1_0
- r::r-dichromat=2.0_0=r3.3.1_2
- r::r-dplyr=0.4.3=r3.3.1_0
- r::r-foreign=0.8_66=r3.3.1_0
- r::r-formula=1.2_1=r3.3.1_0
- r::r-gdata=2.17.0=r3.3.1_0
- r::r-gridextra=2.2.1=r3.3.1_0
- r::r-gtable=0.2.0=r3.3.1_0
- r::r-gtools=3.5.0=r3.3.1_0
- r::r-hmisc=3.17_4=r3.3.1_0
- r::r-kernsmooth=2.23_15=r3.3.1_0
- r::r-labeling=0.3=r3.3.1_2
- r::r-lattice=0.20_33=r3.3.1_0
- r::r-latticeextra=0.6_28=r3.3.1_0
- r::r-lazyeval=0.2.0=r3.3.1_0
- r::r-mass=7.3_45=r3.3.1_0
- r::r-matrix=1.2_6=r3.3.1_0
- r::r-mgcv=1.8_12=r3.3.1_0
- r::r-munsell=0.4.3=r3.3.1_0
- r::r-nlme=3.1_128=r3.3.1_0
- r::r-nnet=7.3_12=r3.3.1_0
- r::r-plyr=1.8.4=r3.3.1_0
- r::r-r6=2.1.2=r3.3.1_0
- r::r-rcolorbrewer=1.1_2=r3.3.1_3
- r::r-rcpp=0.12.5=r3.3.1_0
- r::r-rcpparmadillo=0.7.100.3.1=r3.3.1_0
- r::r-rcurl=1.95_4.8=r3.3.1_0
- r::r-recommended=3.3.1=r3.3.1_0
- r::r-reshape2=1.4.1=r3.3.1_2
- r::r-rpart=4.1_10=r3.3.1_0
- r::r-rsqlite=1.0.0=r3.3.1_2
- r::r-scales=0.4.0=r3.3.1_0
- r::r-spatial=7.3_11=r3.3.1_0
- r::r-stringi=1.1.1=r3.3.1_0
- r::r-stringr=1.0.0=r3.3.1_0
- r::r-survival=2.39_4=r3.3.1_0
- r::r-xml=3.98_1.4=r3.3.1_0
- r::r-xtable=1.8_2=r3.3.1_0
- reportlab=3.3.0=py35_0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - tables==3.3.0
prefix: /home/cmb-panasas2/skchoudh/software_frozen/anaconda2/envs/clipseq

